/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Seguridad;

import Mantenimientos.Frm_Centro_Distribucion;
import Mantenimientos.Frm_Product;
import Mantenimientos.Frm_Rack;
import Mantenimientos.Frm_WH;

/**
 *
 * @author Gustavo
 */
public class Frm_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    Frm_Login login = new Frm_Login();
    public Frm_MenuPrincipal(Frm_Login log) {
        initComponents();
        login=log;
        
    }
    public Frm_MenuPrincipal() {
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_principal = new javax.swing.JMenuBar();
        menu_mantenimientos = new javax.swing.JMenu();
        op_Centro_distribucion = new javax.swing.JMenuItem();
        op_Personal = new javax.swing.JMenuItem();
        op_Producto = new javax.swing.JMenuItem();
        op_Almacenes = new javax.swing.JMenuItem();
        op_Racks = new javax.swing.JMenuItem();
        op_Pallet = new javax.swing.JMenuItem();
        menu_operaciones = new javax.swing.JMenu();
        op_Internamiento_Productos = new javax.swing.JMenuItem();
        op_Salida_Productos = new javax.swing.JMenuItem();
        op_Movimiento_Interno = new javax.swing.JMenuItem();
        op_Carga_Datos = new javax.swing.JMenuItem();
        menu_seguridad = new javax.swing.JMenu();
        op_Perfiles = new javax.swing.JMenuItem();
        op_Usuarios = new javax.swing.JMenuItem();
        op_Cambio_Contraseña = new javax.swing.JMenuItem();
        menu_reportes = new javax.swing.JMenu();
        op_Reporte_Internamiento = new javax.swing.JMenuItem();
        op_Guia_Transportista = new javax.swing.JMenuItem();
        op_Reporte_Despacho = new javax.swing.JMenuItem();
        op_Reporte_diferencia_Inventario = new javax.swing.JMenuItem();
        op_Reporte_Kardex_segun_fecha = new javax.swing.JMenuItem();
        op_Reporte_Stock_fecha = new javax.swing.JMenuItem();
        op_Reporte_Libre_disponibilidad = new javax.swing.JMenuItem();
        menu_cerrarsesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_mantenimientos.setText("Mantenimientos");

        op_Centro_distribucion.setText("Centro de Distribución");
        op_Centro_distribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_Centro_distribucionActionPerformed(evt);
            }
        });
        menu_mantenimientos.add(op_Centro_distribucion);

        op_Personal.setText("Personal");
        op_Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_PersonalActionPerformed(evt);
            }
        });
        menu_mantenimientos.add(op_Personal);

        op_Producto.setText("Productos");
        op_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_ProductoActionPerformed(evt);
            }
        });
        menu_mantenimientos.add(op_Producto);

        op_Almacenes.setText("Almacenes");
        op_Almacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_AlmacenesActionPerformed(evt);
            }
        });
        menu_mantenimientos.add(op_Almacenes);

        op_Racks.setText("Racks");
        op_Racks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_RacksActionPerformed(evt);
            }
        });
        menu_mantenimientos.add(op_Racks);

        op_Pallet.setText("Pallet");
        menu_mantenimientos.add(op_Pallet);

        menu_principal.add(menu_mantenimientos);

        menu_operaciones.setText("Operaciones");

        op_Internamiento_Productos.setText("Internamiento de Productos");
        menu_operaciones.add(op_Internamiento_Productos);

        op_Salida_Productos.setText("Salida de  Productos");
        menu_operaciones.add(op_Salida_Productos);

        op_Movimiento_Interno.setText("Movimiento Interno");
        menu_operaciones.add(op_Movimiento_Interno);

        op_Carga_Datos.setText("Carga de Datos");
        op_Carga_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_Carga_DatosActionPerformed(evt);
            }
        });
        menu_operaciones.add(op_Carga_Datos);

        menu_principal.add(menu_operaciones);

        menu_seguridad.setText("Seguridad");

        op_Perfiles.setText("Perfiles");
        menu_seguridad.add(op_Perfiles);

        op_Usuarios.setText("Usuarios");
        op_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_UsuariosActionPerformed(evt);
            }
        });
        menu_seguridad.add(op_Usuarios);

        op_Cambio_Contraseña.setText("Cambio de Contraseña");
        op_Cambio_Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_Cambio_ContraseñaMouseClicked(evt);
            }
        });
        op_Cambio_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_Cambio_ContraseñaActionPerformed(evt);
            }
        });
        menu_seguridad.add(op_Cambio_Contraseña);

        menu_principal.add(menu_seguridad);

        menu_reportes.setText("Reportes");

        op_Reporte_Internamiento.setText("Reporte de Internamiento");
        menu_reportes.add(op_Reporte_Internamiento);

        op_Guia_Transportista.setText("Guia de Transportista ");
        menu_reportes.add(op_Guia_Transportista);

        op_Reporte_Despacho.setText("Reporte de Despacho");
        menu_reportes.add(op_Reporte_Despacho);

        op_Reporte_diferencia_Inventario.setText("Reporte de diferencia de Inventario");
        menu_reportes.add(op_Reporte_diferencia_Inventario);

        op_Reporte_Kardex_segun_fecha.setText("Reporte de Kardex segun fecha");
        menu_reportes.add(op_Reporte_Kardex_segun_fecha);

        op_Reporte_Stock_fecha.setText("Reporte de Stock a la fecha");
        op_Reporte_Stock_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_Reporte_Stock_fechaActionPerformed(evt);
            }
        });
        menu_reportes.add(op_Reporte_Stock_fecha);

        op_Reporte_Libre_disponibilidad.setText("Reporte de Libre disponibilidad");
        menu_reportes.add(op_Reporte_Libre_disponibilidad);

        menu_principal.add(menu_reportes);

        menu_cerrarsesion.setText("Cerrar Sesión");
        menu_cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_cerrarsesionMouseClicked(evt);
            }
        });
        menu_principal.add(menu_cerrarsesion);

        setJMenuBar(menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op_PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_PersonalActionPerformed
        // TODO add your handling code her
        
    }//GEN-LAST:event_op_PersonalActionPerformed

    private void op_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_UsuariosActionPerformed

    private void op_Reporte_Stock_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_Reporte_Stock_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_Reporte_Stock_fechaActionPerformed

    private void op_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_ProductoActionPerformed
        Frm_Product frmProducts = new Frm_Product(this);
        frmProducts.setVisible(true);
        frmProducts.setLocation(450, 150);        
        this.setEnabled(false);
    }//GEN-LAST:event_op_ProductoActionPerformed

    private void op_Carga_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_Carga_DatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_Carga_DatosActionPerformed

    private void menu_cerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_cerrarsesionMouseClicked
        // TODO add your handling code here:
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_cerrarsesionMouseClicked

    private void op_Cambio_ContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_Cambio_ContraseñaMouseClicked
        // TODO add your handling code here:
       
         
    }//GEN-LAST:event_op_Cambio_ContraseñaMouseClicked

    private void op_Cambio_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_Cambio_ContraseñaActionPerformed
        // TODO add your handling code here:
          frm_Restablecer_contrasena frmRestablecer_contrasena = new frm_Restablecer_contrasena(this);
         frmRestablecer_contrasena.setVisible(true);
         frmRestablecer_contrasena.setLocation(450, 150);
         this.setVisible(false);
    }//GEN-LAST:event_op_Cambio_ContraseñaActionPerformed

    private void op_Centro_distribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_Centro_distribucionActionPerformed
        // TODO add your handling code here:
        Frm_Centro_Distribucion frm_centro_distribucion = new Frm_Centro_Distribucion(this);
        frm_centro_distribucion.setVisible(true);
        frm_centro_distribucion.setLocation(450, 150);
         this.setVisible(false);
    }//GEN-LAST:event_op_Centro_distribucionActionPerformed

    private void op_RacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_RacksActionPerformed
        // TODO add your handling code here:
        Frm_Rack frm_rack = new Frm_Rack(this);
        frm_rack.setVisible(true);
        frm_rack.setLocation(450, 150);
        this.setVisible(false);
    }//GEN-LAST:event_op_RacksActionPerformed

    private void op_AlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_AlmacenesActionPerformed
        // TODO add your handling code here:
        Frm_WH frm_wh = new Frm_WH(this);
        frm_wh.setVisible(true);
        frm_wh.setLocation(450, 150);
        this.setVisible(false);
    }//GEN-LAST:event_op_AlmacenesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menu_cerrarsesion;
    private javax.swing.JMenu menu_mantenimientos;
    private javax.swing.JMenu menu_operaciones;
    private javax.swing.JMenuBar menu_principal;
    private javax.swing.JMenu menu_reportes;
    private javax.swing.JMenu menu_seguridad;
    private javax.swing.JMenuItem op_Almacenes;
    private javax.swing.JMenuItem op_Cambio_Contraseña;
    private javax.swing.JMenuItem op_Carga_Datos;
    private javax.swing.JMenuItem op_Centro_distribucion;
    private javax.swing.JMenuItem op_Guia_Transportista;
    private javax.swing.JMenuItem op_Internamiento_Productos;
    private javax.swing.JMenuItem op_Movimiento_Interno;
    private javax.swing.JMenuItem op_Pallet;
    private javax.swing.JMenuItem op_Perfiles;
    private javax.swing.JMenuItem op_Personal;
    private javax.swing.JMenuItem op_Producto;
    private javax.swing.JMenuItem op_Racks;
    private javax.swing.JMenuItem op_Reporte_Despacho;
    private javax.swing.JMenuItem op_Reporte_Internamiento;
    private javax.swing.JMenuItem op_Reporte_Kardex_segun_fecha;
    private javax.swing.JMenuItem op_Reporte_Libre_disponibilidad;
    private javax.swing.JMenuItem op_Reporte_Stock_fecha;
    private javax.swing.JMenuItem op_Reporte_diferencia_Inventario;
    private javax.swing.JMenuItem op_Salida_Productos;
    private javax.swing.JMenuItem op_Usuarios;
    // End of variables declaration//GEN-END:variables
}
